name: Verify Peribolos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  project:
    name: Verify peribolos
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: './go.mod'

      - name: verify go modules and vendor directory
        run: |
          go mod tidy
          go mod vendor

      - name: running unit tests
        run: |
          go test ./...

      - name: Install yamllint and check peribolos.yaml
        run: pip install yamllint && yamllint peribolos.yaml
